### ISSUE TITLE
error in converting to annovar db format

### ISSUE THREAD

**Issue by hjaytee** [mobidic/update_annovar_db#2]
hello
i need some help with this script. i am running the following script just like the example:
python update_annovar_db-main/update_resources.py -d clinvar -hp /path/to/annovar/humandb -a /path/to/annovar -g GRCh37
the issue is after execution the compressed vcf file was completely downloaded. the converting was successfully done, but the final output is empty (both avinput and txt files).

[INFO]: Mon May 29 13:20:04 2023 - ClinVar distant md5: 23bc53751ae10f6edfa2df41412fd487
[INFO]: Mon May 29 13:20:04 2023 - ClinVar local md5: no previous file
[INFO]: Mon May 29 13:22:13 2023 - Downloading file as clinvar/GRCh37/clinvar_20230527.vcf.gz
[INFO]: Mon May 29 13:22:21 2023 - Downloading file as clinvar/GRCh37/clinvar_20230527.vcf.gz.md5
[INFO]: Mon May 29 13:22:23 2023 - Downloading file as clinvar/GRCh37/clinvar_20230527.vcf.gz.tbi
[INFO]: Mon May 29 13:22:23 2023 - Successfully downloaded and checked ClinVar file clinvar_20230527.vcf.gz
[INFO]: Mon May 29 13:22:23 2023 - Launching ANNOVAR convert2annovar on clinvar_20230527.vcf.gz
[INFO]: Mon May 29 13:22:23 2023 - ANNOVAR successfully created clinvar/GRCh37/clinvar_20230527.avinput
[INFO]: Mon May 29 13:22:23 2023 - Launching CUSTOM conversion to ANNOVAR db format on clinvar/GRCh37/clinvar_20230527.avinput
[INFO]: Mon May 29 13:22:24 2023 - File successfully converted to ANNOVAR db format clinvar/GRCh37/clinvar_20230527.txt
[INFO]: Mon May 29 13:22:24 2023 - Launching ANNOVAR indexing on /media/hossein/My-Passport/linux-shared/finall/annovar/humandb/clinvar_20230527.txt

i am glad to hear from you if there are some tips that i forgot.
thanks
[clinvar_20230527.txt](https://github.com/mobidic/update_annovar_db/files/11590267/clinvar_20230527.txt)

**Comment by vidboda** [comment]
Hi,

if the avinput is empty, then the convert2annovar failed. I suppose your version of the annovar is the most recent one? Could you  test the conversion manually (i.e. launching annovar convert2annovar with the clinvar file) and check what happens?

**Comment by vidboda** [comment]
I just ran it with the same clinvar VCF (20230527) and everything went fine (annovar 2020June08).

In addition did you run the [test](https://github.com/mobidic/update_annovar_db/tree/main#test) successfully?

**Comment by hjaytee** [comment]
hi, 
i used the following script to convert vcf:
convert2annovar.pl -format vcf4 clinvar_20230527.vcf.gz -outfile clinvar.avinput -includeinfo

the avinput was made, then changed the name to clivar test and convert it to text. is that ok?

**Comment by hjaytee** [comment]
the test with the sample avinput file goes well. the problem is the created avinput file. is has no data. i dont now if manual conversion and then converting it annovar db with test script will works or not.

**Comment by vidboda** [comment]
> the avinput was made, then changed the name to clivar test and convert it to text. is that ok?

Well if you used the avinput2annovardb.py script for the conversion it should just be fine. Just test it within an annovar analysis and check the clinvar annotations.

It would be interesting to understand why the complete run did not work, but only with what you wrote I cannot investigate much.

**Comment by vidboda** [comment]
no updates - close
